package com.chatestoque;

public enum EstadoConversa {
    AGUARDANDO_COMANDO,
    AGUARDANDO_NOME_USUARIO,
    AGUARDANDO_ID,
    AGUARDANDO_NOME,
    AGUARDANDO_TAMANHO,
    AGUARDANDO_COR,
    AGUARDANDO_QUANTIDADE,
    AGUARDANDO_COMPRA,
    AGUARDANDO_TAMANHO_COMPRA,
    AGUARDANDO_ENDERECO,
    AGUARDANDO_CONFIRMACAO_ENDERECO,
    AGUARDANDO_CPF, AGUARDANDO_PAGAMENTO
}